In [1]:
Movies = [[1,2,3],[4,5,6],[7,8,9]]

In [2]:
Movies

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
Movies[1][1]

5

In [1]:
import numpy as np

In [2]:
#creating a 3D array
students = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
students

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#using indexing to locate a particular object in an array 
students[2,2]

np.int64(9)

In [5]:
#using .shape to get the shape of the array;if it is a 2 by 2 or 3 by 3 matrix
students.shape

(3, 3)

In [ ]:
#creating a 2D array
course = np.array([[1,2,3],[4,5,6]])

In [8]:
course

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#creating a list
b = [[1,2,3],[4,5,6],[7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
type(b)

list

In [11]:
c = np.array(b)

In [12]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
type(c)

numpy.ndarray

In [14]:
c[1,1]

np.int64(5)

In [15]:
c[1,2] = 12

In [16]:
c

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [17]:
print(c[0,0],c[1,0],c[2,0])

1 4 7


In [18]:
#creating a multidimensional array
w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[26,27,28]]])
print(w, '\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [26 27 28]]] 



In [19]:
w.shape

(3, 3, 3)

In [21]:
w[0,0,0]

np.int64(1)

In [22]:
w[1,2,1]

np.int64(17)

In [23]:
print(w[0,0,0],w[0,1,1],w[0,2,2],w[1,0,0],w[1,1,1],w[1,2,2],w[2,0,0],w[2,1,1],w[2,2,2])

1 5 9 10 14 18 19 23 28


In [24]:
numbers = np.arange(20)
print(numbers)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
#.reshape changes a vector to a matrix
new_numbers = numbers.reshape(2,10)

print(new_numbers)
#print("The shape of

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [31]:
#.zeros is used to create an array filled with zeros

digits = np.zeros((4,4))

digits

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
#.ones create an array filled with ones
figures = np.ones((2,4))

figures

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
#.full creates an array filled with a specified given value
scores = np.full((2,3), 15)

scores

array([[15, 15, 15],
       [15, 15, 15]])

In [34]:
new_scores = np.full((4,5), 3)

new_scores

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [35]:
#.eye function lets you create a n * n diagonal matrix

np_eye = np.eye(5,20)

np_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [37]:
np_eye = np.eye(15,15)

np_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [40]:
#.linspace returns evenly spaced numbers over a specified interval
#examples

np_linspace = np.linspace(1, 5, num = 3)

np_linspace

array([1., 3., 5.])

In [41]:
figures = np.linspace(1, 20, num = 5)

figures

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [47]:
#.random random creates an array filled with random values between o and 1
np_rand = np.random.random((2,3))

np_rand

array([[0.83172906, 0.87393658, 0.14300137],
       [0.49508883, 0.98931205, 0.5651564 ]])

In [48]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[26,27,28]]])
print(w, '\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [26 27 28]]] 



In [78]:
w[1:2]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [79]:
w[1:2,0:2]

array([[[10, 11, 12],
        [13, 14, 15]]])

In [80]:
w[1:2,0:2,1:]

array([[[11, 12],
        [14, 15]]])

In [56]:
#slicing an array
#examples
w[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
w[0,0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [60]:
w[2]

array([[19, 20, 21],
       [22, 23, 24],
       [26, 27, 28]])

In [64]:
w[2,0:3,0:2]

array([[19, 20],
       [22, 23],
       [26, 27]])

In [65]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a[0::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
a[0::, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [71]:
a[1::, 0:2]

array([[ 5,  6],
       [ 9, 10]])

In [72]:
a[1::,2:4]

array([[ 7,  8],
       [11, 12]])

In [77]:
a[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [3]:
import numpy as np


In [5]:
new = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [6]:
new.dtype

dtype('int64')

In [7]:
new.shape

(5, 3)

In [8]:
new.ndim

2

In [9]:
new.size

15

In [10]:
import pandas as pd